Traceback (most recent call last):
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import psi4
mol_tmpl = """
C
O 1 **R**
symmetry c2v
"""

r_angstrom = np.array([0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1])
options_dict = {
    "basis": "cc-pVTZ",
    "e_convergence": 1e-10,
    "d_convergence": 1e-10,
}

psi4.set_options(options_dict)
#mol = psi4.geometry(mol_tmpl)

#ccsdt_e = psi4.energy('ccsd')

ccsdt_energy = []

for r_val in r_angstrom:
    mol_str = mol_tmpl.replace("**R**", str(r_val))
    mol = psi4.geometry(mol_str)
    ccsdt_e = psi4.energy('ccsd')
    ccsdt_energy.append(ccsdt_e)

------------------


[31m---------------------------------------------------------------------------[39m
[31mImportError[39m                               Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[13][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mpsi4[39;00m
[32m      2[39m mol_tmpl = [33m"""[39m
[32m      3[39m [33mC[39m
[32m      4[39m [33mO 1 **R**[39m
[32m      5[39m [33msymmetry c2v[39m
[32m      6[39m [33m"""[39m
[32m      8[39m r_angstrom = np.array([[32m0.6[39m, [32m0.7[39m, [32m0.8[39m, [32m0.9[39m, [32m1.0[39m, [32m1.1[39m, [32m1.2[39m, [32m1.3[39m, [32m1.4[39m, [32m1.5[39m, [32m1.6[39m, [32m1.7[39m, [32m1.8[39m, [32m1.9[39m, [32m2.0[39m, [32m2.1[39m])

[36mFile [39m[32m~/Code/psi4/objdir-Release/stage/lib/psi4/__init__.py:71[39m
[32m     68[39m data_dir = [38;5;28mstr[39m(data_dir)
[32m     70[39m [38;5;66;03m# Init core[39;00m
[32m---> [39m[32m71[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01m.[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m core
[32m     73[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mpsi4[39;00m[34;01m.[39;00m[34;01mcore[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m get_num_threads, set_num_threads
[32m     74[39m core.initialize()

[31mImportError[39m: cannot import name 'core' from partially initialized module 'psi4' (most likely due to a circular import) (/Users/jfoley19/Code/psi4/objdir-Release/stage/lib/psi4/__init__.py)

